<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="61344" started-at="2018-06-02T17:58:04Z" finished-at="2018-06-02T17:59:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="61344" started-at="2018-06-02T17:58:04Z" finished-at="2018-06-02T17:59:05Z">
      <class name="testscipt.Test4">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testscipt.Test4@77ec78b9]" name="launchBrowser" is-config="true" duration-ms="4727" started-at="2018-06-02T17:58:04Z" finished-at="2018-06-02T17:58:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="testtwitterHome()[pri:0, instance:testscipt.Test4@77ec78b9]" name="testtwitterHome" duration-ms="54682" started-at="2018-06-02T17:58:08Z" finished-at="2018-06-02T17:59:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at testscipt.Test4.testtwitterHome(Test4.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtwitterHome -->
        <test-method status="PASS" signature="closeBrowser(org.testng.ITestResult)[pri:0, instance:testscipt.Test4@77ec78b9]" name="closeBrowser" is-config="true" duration-ms="1876" started-at="2018-06-02T17:59:03Z" finished-at="2018-06-02T17:59:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testtwitterHome status=FAILURE method=Test4.testtwitterHome()[pri:0, instance:testscipt.Test4@77ec78b9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testscipt.Test4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
